apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: applications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:

